### PR TITLE
Update to clang-format version 11

### LINKED ISSUE #57: Update version of clang-format to v.11 to be consistent with deal.II master
@peterrum @kronbichler I suggest to update the CI's version of `clang-format` to v.11 for the indentation check to be consistent with current deal.II master. If you agree, I'll resolve this issue in a PR.

### PR DESCRIPTION
**Pull request by mschreter**
... resolves #57

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
I think you missed one file.

**Comment by mschreter** [comment]
> I think you missed one file.

Unfortunately not, CI produces a different result than the local clang-format:

```
diff --git a/applications/micro_particle.cc b/applications/micro_particle.cc
index 0e804d6..8f8ed63 100644
--- a/applications/micro_particle.cc
+++ b/applications/micro_particle.cc
@@ -542,7 +542,7 @@ main(int argc, char **argv)
 
   // change mode for rounding: denormals are flushed to zero to avoid computing
   // on denormals which can slow down things.
-#define MXCSR_DAZ (1 << 6)  /* Enable denormals are zero mode */
+#define MXCSR_DAZ (1 << 6) /* Enable denormals are zero mode */
 #define MXCSR_FTZ (1 << 15) /* Enable flush to zero mode */
```

**Comment by peterrum** [comment]
> Unfortunately not, CI produces a different result than the local clang-format:

I don't know. For some reason, the comments are aligned. I guess if you add a new lines between the ifdefs that should fix the issue.

**Comment by peterrum** [comment]
@mschreter I took the liberty to push onto your branch so that we can merge this as soon as possible and you can proceed to rebase the other branch. @kronbichler Do you agree with updating clang-format if yes I'll merge?

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
