### PR TITLE
Modify get_hypercube to fix compatibility issues with current deal.ii master

### PR DESCRIPTION
**Pull request by mschreter**

### CODE REVIEW

**Comment by mschreter** [comment]
I think this PR is related to this PR https://github.com/dealii/dealii/pull/11602.

**Review by peterrum — APPROVED** [review]
Thanks!

**Comment by peterrum** [comment]
I guess you have compiled the code successfully locally. If yes, I think the failing test here is related to the deal.II docker image being not up to date. If this is the case, feel free to merge!

**Comment by mschreter** [comment]
Yes, I was able to compile it locally. The docker image and the merging appeared almost at the same time. Let's wait a bit until the docker image will be updated.

**Comment by peterrum** [comment]
OK. I will restart the test in a couple of hours! 

This is why I wrote on the slides of the workshop: "last resort". People should not use these function, they are meant primarily for internal usage (and for people who think they know what they do^^).

**Comment by peterrum** [comment]
The issue is more serious. All GitHub actions related to the Docker images fail: https://github.com/dealii/dealii/actions?query=workflow%3Agithub-docker

**Comment by peterrum** [comment]
Let's merge and I will sort out the issue tomorrow.

**Comment by peterrum** [comment]
@mschreter Btw, thanks a lot. I completely forgot that we are using this function...

**Pull request merged**
